// ─────────────────────────────────────────────────────────────
// TiketFlow ticket card image — a shareable PNG that pairs the
// buyer's QR code with the event details, branded as TiketFlow.
// Used for WhatsApp/email delivery and on-page card downloads.
// ─────────────────────────────────────────────────────────────
import { toDataURL } from 'qrcode';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://tiketflow.vercel.app';

function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

// Only allow hex colours (e.g. #a855f7) into SVG attributes — prevents any
// attribute breakout from organiser-supplied values.
function safeColor(c, fallback = '#7c3aed') {
  return /^#[0-9a-fA-F]{3,8}$/.test(String(c || '')) ? String(c) : fallback;
}

function formatDate(d) {
  try {
    return new Date(d).toLocaleDateString('en-US', { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric' });
  } catch { return d || ''; }
}

/**
 * Build the SVG markup for a ticket card (no QR yet — injected as data URL).
 * 800x1130 portrait — looks good in WhatsApp chats & email.
 */
function buildCardSvg({ event, ticket, ticketType, qrDataUrl }) {
  const accent = safeColor(event?.theme_color);
  const isFree = !!ticketType && Number(ticketType.price) === 0;
  const priceLabel = isFree ? 'FREE ADMISSION' : `USD ${Number(ticketType?.price || 0).toFixed(2)}`;

  // Row helper: label left, value right
  const row = (label, value, y) => `
    <text x="56" y="${y}" font-family="sans-serif" font-size="22" fill="#8b8fa3">${esc(label)}</text>
    <text x="744" y="${y}" font-family="sans-serif" font-size="22" font-weight="bold" fill="#15192b" text-anchor="end">${esc(value)}</text>`;

  return `
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="800" height="1130" viewBox="0 0 800 1130">
  <defs>
    <linearGradient id="header" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${accent}"/>
      <stop offset="100%" stop-color="${accent}bb"/>
    </linearGradient>
  </defs>

  <!-- Card background -->
  <rect width="800" height="1130" rx="48" fill="#ffffff"/>

  <!-- Branded header -->
  <rect x="0" y="0" width="800" height="300" fill="url(#header)"/>
  <text x="400" y="92" font-family="sans-serif" font-size="26" font-weight="bold" letter-spacing="10" fill="rgba(255,255,255,0.85)" text-anchor="middle">TIKETFLOW</text>
  <text x="400" y="165" font-family="sans-serif" font-size="44" font-weight="bold" fill="#ffffff" text-anchor="middle">${esc(event?.event_name || 'Event')}</text>
  <text x="400" y="212" font-family="sans-serif" font-size="24" fill="rgba(255,255,255,0.9)" text-anchor="middle">${esc(ticketType?.name || 'Ticket')}</text>

  <!-- Price pill -->
  <rect x="400" y="242" width="${isFree ? 300 : 240}" height="44" rx="22" fill="rgba(255,255,255,0.22)"/>
  <text x="400" y="272" font-family="sans-serif" font-size="22" font-weight="bold" fill="#ffffff" text-anchor="middle">${esc(priceLabel)}</text>

  <!-- QR code -->
  <rect x="200" y="340" width="400" height="400" rx="24" fill="#f6f7fb"/>
  <image xlink:href="${qrDataUrl}" x="230" y="370" width="340" height="340"/>

  <!-- Token -->
  <text x="400" y="790" font-family="monospace, sans-serif" font-size="20" fill="#9aa0b4" text-anchor="middle">${esc(String(ticket?.qr_code_token || '').slice(0, 8).toUpperCase())} •••• ${esc(String(ticket?.qr_code_token || '').slice(-4).toUpperCase())}</text>

  <!-- Details -->
  ${row('Ticket Holder', ticket?.buyer_name, 870)}
  ${row('Date', formatDate(event?.date), 930)}
  ${row('Time', event?.time || '—', 990)}
  ${row('Venue', event?.venue || '—', 1050)}

  <!-- Footer strip -->
  <rect x="0" y="1082" width="800" height="48" rx="0" fill="#f1f2f7"/>
  <text x="400" y="1111" font-family="sans-serif" font-size="17" fill="#8b8fa3" text-anchor="middle">Show this QR code at the gate · Generated by TiketFlow</text>
</svg>`;
}

/**
 * Generate the PNG buffer for a ticket card.
 * @returns {Promise<Buffer>} PNG image
 */
export async function generateTicketCardPng({ ticket, event, ticketType }) {
  const ticketUrl = `${SITE_URL}/ticket/${ticket?.qr_code_token || ''}`;
  const qrDataUrl = await toDataURL(ticketUrl, {
    width: 340,
    margin: 1,
    errorCorrectionLevel: 'H',
    color: { dark: '#15192b', light: '#ffffff' },
  });

  const svg = buildCardSvg({ event, ticket, ticketType, qrDataUrl });

  // lazy-require sharp so this module is safe to import on the client too
  const sharp = (await import('sharp')).default;
  return sharp(Buffer.from(svg)).png().toBuffer();
}

